name: test_app
description: A Flutter application for credit calculations.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner:
  sqflite:
  path: ^1.8.3
  get:
  intl:
  flutter_typeahead: ^4.6.2
  flutter_slidable: ^3.0.0
  cupertino_icons:
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  drift: ^2.9.0
  path_provider: ^2.0.15
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  build_runner: ^2.4.5
  drift_dev: ^2.9.0
  json_serializable: ^6.7.0

flutter_native_splash:
  background_image: "assets/splash.png"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/lunchicon.png"
flutter:
  uses-material-design: true

  fonts:
    - family: Barcode
      fonts:
        - asset: assets/Barcode.ttf
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
